name: openMINDS_upstream

on:
  push:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger central repository
      run: |
        curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/HumanBrainProject/openMINDS/actions/workflows/build.yml/dispatches --data '{"ref": "main"}'
        curl -XPOST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/openMetadataInitiative/openMINDS_pipeline/actions/workflows/build.yml/dispatches --data '{"ref": "${GITHUB_REF##*/}" }'
